services:
  - type: web
    name: healthcare-insurance-prediction
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
